### Create product
POST http://localhost:3000/product
Content-Type: application/json

{
  "name":"",
  "price":1,
  "quantity":1,
  "description":""
}
### Update product
PUT http://localhost:3000/product/<id>
Content-Type: application/json

{
  "name":"",
  "price":1212,
  "quantity":2112,
  "description":""
}

### Get products
GET http://localhost:3000/product



### Get product
GET http://localhost:3000/product/<id>



### Delete product
DELETE http://localhost:3000/product/<id>